language: csharp
mono:
    - latest
    - 4.6.2
    - 4.8.1
dotnet: 
    - 2.0.0
install:
    - nuget restore SharpNoise.sln
    - nuget restore Examples/SharpNoiseSamples.sln
    - dotnet restore
script:
    - xbuild /p:TargetFrameworkVersion="v4.5" /p:Configuration=Release SharpNoise.sln
    - xbuild /p:TargetFrameworkVersion="v4.5" /p:Configuration=Debug SharpNoise.sln
    - xbuild /p:TargetFrameworkVersion="v4.5" /p:Configuration=Release Examples/SharpNoiseSamples.sln
    - xbuild /p:TargetFrameworkVersion="v4.5" /p:Configuration=Debug Examples/SharpNoiseSamples.sln
    - mono ./packages/xunit.runner.console.*/tools/xunit.console.exe ./SharpNoise.Tests/bin/Release/SharpNoise.Tests.dll
    - mono ./packages/xunit.runner.console.*/tools/xunit.console.exe ./SharpNoise.Tests/bin/Debug/SharpNoise.Tests.dll
    - dotnet build