language: csharp
mono:
    - latest
install:
    - nuget restore SharpNoise.sln
    - nuget restore Examples/SharpNoiseSamples.sln
script:
    - msbuild /p:TargetFrameworkVersion="v4.5" /p:Configuration=Release SharpNoise.sln
    - msbuild /p:TargetFrameworkVersion="v4.5" /p:Configuration=Debug SharpNoise.sln
    - msbuild /p:TargetFrameworkVersion="v4.5" /p:Configuration=Release Examples/SharpNoiseSamples.sln
    - msbuild /p:TargetFrameworkVersion="v4.5" /p:Configuration=Debug Examples/SharpNoiseSamples.sln
    - mono ./packages/xunit.runner.console.*/tools/xunit.console.exe ./SharpNoise.Tests/bin/Release/SharpNoise.Tests.dll
    - mono ./packages/xunit.runner.console.*/tools/xunit.console.exe ./SharpNoise.Tests/bin/Debug/SharpNoise.Tests.dll
